### ISSUE TITLE
Enable ESLint package updates in dependabot config

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#1841]
Updates to the ESLint package have been disabled because there was a conflict with an eslint plugin.
https://stackoverflow.com/questions/69578685/eslint-broken-rules-with-suggestions-must-set-the-meta-hassuggestions-propert
The react hooks plugin has not yet had a stable release that includes the changes required for ESLint 8.
So for now we will keep using ESLint 7.
This ticket serves as a reminder to occasionally check if we can move to ESLint 8.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/1841?planning-poker) with ZenHub @bartv @Stijnkool
