### ISSUE TITLE
Replace all Class Components with Functional Components

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#1862]
There are still some Class Components in the code base.
This is a supported way of writing components.
But is not the preferred way. All our new components have been written as Functional Components.
We should move the current Class Components over to Functional Components.

Class Components:
- IconDropdown
- SimpleBackgroundImage

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/1862?planning-poker) with ZenHub @bartv @Stijnkool
