### ISSUE TITLE
Bundle size optimisations

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#1863]
### Overview
Bundle size is not a big issue. But it's still worth improving a bit.
Code that gets shipped needs to be downloaded and parsed.

![Screenshot 2021-11-04 at 17.16.31.png](https://images.zenhubusercontent.com/5ff6d00bc83e866b30a3b040/d954304d-5c43-4ddb-8408-beff9ec13675)

### Should we switch from lodash to lodash-es?
Maybe this will improve tree-shaking. This will not include the whole lodash lib, just the methods we need.
https://stackoverflow.com/questions/35250500/correct-way-to-import-lodash

### Why are we including all momentjs locales?
Just including the english locale might be enough and will win us a lot.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/1863?planning-poker) with ZenHub @bartv @Stijnkool

**Comment by wouterdb** [comment]
timebox to estimated size
