### ISSUE TITLE
Use react-markdown in DeleteEnvModal

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#1890]
blocked by https://github.com/facebook/jest/issues/9430
related to https://github.com/inmanta/web-console/issues/1798

Use ReactMarkdown for bold and italics: https://www.npmjs.com/package/react-markdown
The words module also needs to distinguish between regular text and markdown text.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/1890?planning-poker) with ZenHub @bartv @Stijnkool
