### ISSUE TITLE
Remove old environment mechanism (CommandManager, StateHelper)

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#1923]
This is a continuation of the changes done in the react-router update ticket.
https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/1869

The environment should not be injected in the constructor.
Currently this is still done in StateHelpers and CommandManagers.
QueryManagers have been updated.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/1923?planning-poker) with ZenHub @bartv @Stijnkool
