### ISSUE TITLE
Setup an easy way to test the app with keycloak / authentication

### ISSUE THREAD

**Issue by butterybread** [inmanta/web-console#1930]
This is needed to properly test https://github.com/inmanta/web-console/issues/1724

**Comment by LauraStordeur** [comment]
Hmmm, in the past we had a fake API response in a json file where we updated the userID/JWT-token. This file was in the git-ignore to avoid it landing in the repo. But I don't know in which extent this would be applicable for us. 

We didn't yet use Keycloack, so we were doing the auth call in postman or a custom script that would use credentials stored in a .env file.
