### ISSUE TITLE
Analyse initial loading flow using redux-devtools

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#1960]
Using the redux devtools, we can check every state transition and see how the application is presented.
During actual usage, some of the api calls are so quick, you barely see a transition.
Sometimes you see a flash and ignore it.
With the devtools we can properly analyse these problems.

The main goal of this ticket is to find bugs or inconsistencies that we can improve.
Small things can be fixed immediately. For more substantial changes we should create extra tickets.

This is an example of a view that can be improved:
![Screenshot 2021-11-18 at 13.39.49.png](https://images.zenhubusercontent.com/5ff6d00bc83e866b30a3b040/c427d057-8720-4eac-8a5d-0434c8663279)

- The error message for the sidebar is wrong. The environment is nog missing, it is loading.
The error message is visually unreadable because of the black background.
- The environment selector loading visual is too big for the header, pushing the header down.
- The entire page is black which is inconsistent with the rest off the application.
When loading the application, you see a black flash. I suspect this background is the cause of it.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/1960?planning-poker) with ZenHub @bartv @Stijnkool

**Comment by wouterdb** [comment]
timebox the analysis to 1day

fix easy issues, ticketize other
