### ISSUE TITLE
Improve resource progress bar

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2025]
The next iteration of the progress bar needs some additional improvements:

- It should try to fill the full toolbar, pushing the buttons to the paging component
- The progress bar should be the same height as the buttons
 - When the bar is wide enough, it should show the number like in the service inventory
 - It could use a tooltip that show the states a color includes
 - When a color is clicked, it should select the states in the filter

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2025?planning-poker) with ZenHub @bartv @Stijnkool
