### ISSUE TITLE
disabled state of repair and deploy buttons were stale when switching environments

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2026]
This was visible during a demo. Maybe the isHalted property was outdated.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2026?planning-poker) with ZenHub @Stijnkool @bartv
