### ISSUE TITLE
The web console looses precision on large integers.

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#203]
When a service entity has an integer attribute it is possible that the API returns values that are to large for javascript integers. An example is an order_id attribute which has value 90161132727657997171

![image (24).png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/e292a603-de5f-4165-b602-dbfbffd892e1)

There is no simple fix for this because this data loses precision when the json is loaded from the API. There are a number of solutions:

1. Try to detect it and show it to the user
2. Use a json library that supports large integers: https://www.npmjs.com/package/json-bigint However this needs to be investigated carefully because a bad json library is bad for performance and can create security issues.
3. Let the API also return "string" versions of the value.

For 2 it is also important to think about this when creating or updating instances through the API.

also possible: https://www.npmjs.com/package/lossless-json

We need to evaluate the reliability of the libraries we use.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/203?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
