### ISSUE TITLE
Add indicator of auto-updating to the pages

### ISSUE THREAD

**Issue by andraskvr** [inmanta/web-console#2083]
Most of the pages use data that is continuously updated in the background, however a few of them, for various reasons do not (for example: `Home`, `AgentProcess`).
We should add an indicator (maybe to the top toolbar, an icon with a tooltip?), that the data that the users see is updated automatically or not, to make this clearer.

**Comment by bartv** [comment]
is the alternative to just refresh all the data?

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2083?planning-poker) with ZenHub @andraskvr @Stijnkool
