### ISSUE TITLE
Pause/unpause an individual agent

### ISSUE THREAD

**Issue by andraskvr** [inmanta/web-console#2085]
#1811 mentioned that this would come in a later ticket, but I haven't found it.
It should be possible to pause and unpause one specific agent via the table on the `Agents` page.
The placeholder button is already there.
The v2 `agent_action` endpoint (`/agent/<name>/<action>`) should be used for this. 
This button should be disabled if the environment is halted.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2085?planning-poker) with ZenHub @wouterdb @andraskvr
