### ISSUE TITLE
Add the ability to toggle halt while environment is stopped

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2091]
In the agent table use a toggle switch in the unpause on resume column. Add a tooltip to the toggle that says: "Unpause agent when environment is resumed"

When the environment is not halted the column should be hidden.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2091?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
