### ISSUE TITLE
"Invalid date" for timestamp on Service Instance History

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2116]
See slack archive: https://inmanta.slack.com/archives/CMJFA0RP1/p1638794855176700

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2116?planning-poker) with ZenHub @bartv @Stijnkool
