### ISSUE TITLE
Instance Form slow on Firefox

### ISSUE THREAD

**Issue by andraskvr** [inmanta/web-console#2157]
Followup ticket of #1875
The Create/Edit service instance form is slow on Firefox, when having nested embedded entities.
This is because Patternfly uses `grid` layout for the `FormFieldGroupExpandable` component that we use for showing the inputs for the attributes, and Firefox currently doesn't handle the deeply nested grid layout.
Issue on Firefox bug tracker:
https://bugzilla.mozilla.org/show_bug.cgi?id=1682686

There are a few alternatives for us in this case:

1. Wait for this underlying issue in Firefox to be fixed
2. Recreate the Patternfly component using another layout that doesn't have this problem and looks similar, for example using flexbox
3. Change the styling of this form altogether

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2157?planning-poker) with ZenHub @andraskvr @Stijnkool
