### ISSUE TITLE
Environment Data is handled in a messy way

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2172]
We are fetching and storing environments in a lot of different ways.
We have some classes handling related stuff. It is quite difficult to follow.
We should try to simplify this.
Especially the order of things is hard to follow.
What happens first? Maybe make a diagram to make this clear.

- [ ] document the loading mechanisms for environment
- [ ] if possible, simplify 

Timebox to 1 day

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2172?planning-poker) with ZenHub @bartv @Stijnkool
