### ISSUE TITLE
Import images directly so they also work for local dev

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2198]
The background image urls are hardcoded into the frontend component.
They should be imported and webpack should resolve the urls.
Locally they currently only work when fetched from root /.
Once deployed, they always work.
Maybe the server handles these requests differently.

-> Import the image like any other asset or file, and let webpack handle the rest.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2198?planning-poker) with ZenHub @wouterdb @Stijnkool @andraskvr
