### ISSUE TITLE
Hide loading spinner by default

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2238]
When data is loading, we show a spinner.
Since most calls are really fast, you just see a flash of a spinner.
This is bad UX. We have a feature where we don't show the loading spinner immediately.
We only show it if the calls takes longer than X ms. We currently have it on 500ms.
This feature is only enabled for a few calls. We should make it the default and enable it for everything.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2238?planning-poker) with ZenHub @wouterdb @Stijnkool @andraskvr

**Comment by Stijnkool** [comment]
I have already done this in https://github.com/inmanta/web-console/issues/1960
