### ISSUE TITLE
Cleanup package.json

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2318]
packaged libs should be in `dependencies`.
dev libs should be in `devDependencies`.
for example: `react` & `react-dom` are in the wrong category.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2318?planning-poker) with ZenHub @andraskvr @Stijnkool
