### ISSUE TITLE
Environment selector is out of sync

### ISSUE THREAD

**Issue by andraskvr** [inmanta/web-console#2350]
When creating, modifying or deleting environments, the data in the `EnvironmentSelector` is not updated.
This is likely fallout from the navigation refactor. 
(Since there are multiple redux slices holding similar data, some updates are probably missing. Alternatively the two slices for the environment list - with and without icons - can also be merged).

- [ ] make one redux slice for all environment related stuff.

**Comment by Stijnkool** [comment]
The "Select this environment" button also does not work for a newly created environment. Only after a refresh it works.

**Comment by arnaudsjs** [comment]
> The "Select this environment" button also does not work for a newly created environment. Only after a refresh it works.

FYI: I had this issue on Firefox. I didn't test it with Chrome.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2350?planning-poker) with ZenHub @bartv @andraskvr @Stijnkool
