### ISSUE TITLE
The documentation button links to an incorrect URL when running on the OSS edition

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/web-console#2365]
**Observed behavior:**

`https://docs.inmanta.com/inmanta-service-orchestrator/<major-version-oss-edition>/`

**Desired behavior:**

`https://docs.inmanta.com/community/<version>`

In the status call the product is included. Based on the product it can select iso or community.

**Comment by Stijnkool** [comment]
Yes the documentation link in the frontend code is defined as:
```
return `https://docs.inmanta.com/inmanta-service-orchestrator/${this.featureManager.getServerVersion()}/`;
```
If different behaviour is required, we will need to change it.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2365?planning-poker) with ZenHub @bartv @andraskvr @Stijnkool
