### ISSUE TITLE
Add recompile button to desired state toolbar

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2375]
In the dashboard there is a button to request a recompile (with an optional action to update and recompile).

The goal of this ticket is to add a similar button using the existing APIs to the web-console. This brings us a bit closer to feature parity.

add to both the desired state and compile view 

grey out the button if a compile is running.  (requires a head call, cfr old dashboard)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2375?planning-poker) with ZenHub @bartv @andraskvr @Stijnkool
