### ISSUE TITLE
Add parameters view to the orchestration engine menu

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2377]
The goal is to create an overview table with:

- name
- updated
- source
- value

When the value is to large it should be shortened with hover/copy like in the attributes table

This table should support sorting, filtering and paging as described in [core#3662 ](https://github.com/inmanta/inmanta-core/issues/3662)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2377?planning-poker) with ZenHub @bartv @andraskvr @Stijnkool
