### ISSUE TITLE
Environment boxes appear to be a link but they are not

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/web-console#2383]
In the environment overview page, each environment is represented by a box. When you move your cursor over such a box, the cursor changes into the hand icon indicating it's a link. However, a mouse click doesn't do anything. The link `Select this environment` does navigate to the selected environment.

- [ ] Make the card clickable
- [ ] Move copy and delete to settings. 
- [ ] remove kebab

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2383?planning-poker) with ZenHub @bartv @andraskvr @Stijnkool
