### ISSUE TITLE
Resource log improvements

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2458]
When setting a filter (in the screenshot only the from date) there are two issues:

![image](https://user-images.githubusercontent.com/10819/150532634-bff2c6a2-aeec-4adf-b346-045f32c9dad6.png)

1. The date is cleared but the hour is kept in the filter input. I think both should be cleared
2. The filter chip only show a small portion of the filter. It does not show a tooltip, so there is no way of figuring out what your filter is. The filter chip should be large enough to see the date!

The table itself is also not so useful:

3. On full-hd the message is ellipsed so that it does not show enough useful information even though lots of white space is still available. This should be dynamic so that all white space is used for the message without starting a new line.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2458?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
