### ISSUE TITLE
Resource details tabs miss context

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2465]
When not on the info tab of the resource details, you mis the context of the resource you are inspecting.

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/f46e7f15-1543-4129-8d0b-f47c0819a42c)

The proposal is:

- Remove the current info tab, it does not contain that much information
- The link to the old frontend can be removed
- Add the resource id in a smaller font below the page title (resource ids can be long so putting them in the title will not work)
- The two dates from the info tab should do above the history table. There this information belongs
- Make the desired state tab as the first tab

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2465?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
