### ISSUE TITLE
Handle file content diff in desired state diff

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2486]
When file resources are diffed the content should not compare the resource hashes. It should show a button similar to github/gitlab when a diff would be to large. (only if different of course)

When a user clicks this button, the frontend should fetch both hashes and create a diff

(Data is base64 encoded!!!)

Only required on std::File.hash

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2486?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
