### ISSUE TITLE
Improve environment cards

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2488]
Project name should be bottom aligned on Card (Environment Overview)
![Screenshot 2022-01-24 at 12.51.31.png](https://images.zenhubusercontent.com/5ff6d00bc83e866b30a3b040/c787a121-03f3-4240-8619-be9475593494)

Shouldn't all cards have exactly the same dimensions?
Just leave a fixed amount of space for the description.
It looks very strange if some cards are bigger then others.
Should the cards also be squares?

**Comment by bartv** [comment]
I agree that they should be the same and making them square also sound sane.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2488?planning-poker) with ZenHub @andraskvr @Stijnkool @wouterdb

**Comment by bartv** [comment]
Add the title next to the image as well
