### ISSUE TITLE
Add a matchable resolve method to DeferredApiHelper

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2495]
Currently the resolve method just resolves the next pending request.
It would be good if we have another resolve method that is capable of matching a specific request.
It might also be useful to have an ignore method which is capable of simply removing a pending request if we don't care about it.
This is useful in test cases where some components on a page also fire of requests.
But these components are not the focus of this specific test.

- [ ] Add ignore method for specific requests
- [ ] Add matchable resolve method to resolve specific requests

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2495?planning-poker) with ZenHub @andraskvr @Stijnkool

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2495?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
