### ISSUE TITLE
Result filter on the compile report page is misleading

### ISSUE THREAD

**Issue by andraskvr** [inmanta/web-console#2496]
When selecting the `Failed` option for the result filter on the compile report page
![Screenshot from 2022-01-25 11-55-37.png](https://images.zenhubusercontent.com/5d760d77eb71d10001e8187e/3adddab0-ee95-4b47-abea-c3fb84586954)
The chip and the selected value show strange values:
![Screenshot from 2022-01-25 11-54-48.png](https://images.zenhubusercontent.com/5d760d77eb71d10001e8187e/6b8aa547-6ca1-424d-98b1-b2b530f5b8bb)

The selected option should show `Failed` instead of `false`, and the chip should also show `Failed`, instead of successful.

The backend request is fired correctly.
The issue might be related to how these values are serialized to the url. (The component expects booleans, but they might not be parsed to booleans from the url)

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2496?planning-poker) with ZenHub @andraskvr @Stijnkool @wouterdb
