### ISSUE TITLE
Use the patternfly date and time picker demo component for timerange filters

### ISSUE THREAD

**Issue by andraskvr** [inmanta/web-console#2501]
The patternfly components for selecting date and time are in the beta stage currently, thus they are more difficult to use and error-prone when handling arbitrary user input.
With the following demo, the user can only select predefined time values, select a date with the date selector widget, and cannot manually enter a date or time. So the capabilities are somewhat limited, but the implementation is much simpler, and it might be enough for our use cases as well
https://www.patternfly.org/v4/demos/date-and-time-picker

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2501?planning-poker) with ZenHub @andraskvr @Stijnkool @wouterdb

**Comment by LukasStordeur** [comment]
I'm closing this ticket, there's a related PR that was merged back then, and we are using the timepicker from PF in our codebase.
