### ISSUE TITLE
Make the JsonParser configurable

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2537]
Should we make the support for bigints configurable in general?
This settings should go into the FeatureManager class.

**Comment by bartv** [comment]
Update inmanta-ui extension to add a config option for it and making sure this value gets into config.json

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2537?planning-poker) with ZenHub @andraskvr @Stijnkool @wouterdb
