### ISSUE TITLE
Handle large integers correctly in forms

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2542]
Currently the forms handle numbers as numbers.
Form validation for these fields is also done as numbers.
If we need to support large numbers here, we need to change this.

Options:
- We could use a string representation.
  - Validation needs to be changed
  - When sending data to the API, it needs to be a number again.
This can touch quite some code as the api layer is kept dumb in regards to the data that is transmitted.
It receives data, and sends it along. Turning data into a json string is done implicitly by the Fetch API.
We cant just send a big number to the api layer because this number would lose precision.
If we send a string representing a number then it needs to be turned back into an actual number again.
This might introduce quite some complexity.
- We could use the BigInt native type
  - Validation needs to be changed
  - actual form input might still be a string
  - We can just send a bigInt value to the api layer and it should work.
  - JSON stringifying a bigint is not supported by default.
We can implement is easily as shown in this thread: https://github.com/GoogleChromeLabs/jsbi/issues/30
  - To support BigInt, we need to change our compile target to ES2020.
Currently we compile down to ES2015. There might be other solutions possible.

Both options introduce some complexity and quite some changes.
In general I think supporting BigInt is the way to go.
I think it will introduce the least amount of complexity and will also be the most "correct".

Should all this special handling of large integers be configurable?

1. Support bigint in the number input field
2. Add rationale to design documentation

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2542?planning-poker) with ZenHub @andraskvr @Stijnkool
