### ISSUE TITLE
Support BigInt native type

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2544]
Probably need to change compile target to ES2020.
See what influence this has on type config.
Check browser support for ES2020.
Can we support only BigInt and not the entirety of ES2020?

- [x] ES2020 is fully supported by modern browsers 
https://caniuse.com/?feats=mdn-javascript_operators_optional_chaining,mdn-javascript_operators_nullish_coalescing,mdn-javascript_builtins_globalthis,es6-module-dynamic-import,bigint,mdn-javascript_builtins_promise_allsettled,mdn-javascript_builtins_string_matchall,mdn-javascript_statements_export_namespace,mdn-javascript_statements_import_meta

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2544?planning-poker) with ZenHub @andraskvr @wouterdb

**Comment by bartv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2544?planning-poker) with ZenHub @Stijnkool
