### ISSUE TITLE
Add compare to current state option

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2556]
In the desired state view it should also be possible to select "Compare with current state (dry run)"

When selected this should go to the compliance check page. This page compares a desired state version to the current state by requesting a dryrun from the agent. The agent will send a diff to the server that can be requested by the frontend.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2556?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
