### ISSUE TITLE
Add compliance reporting to the resource manager

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2559]
The new dryrun functionality should be used to create a compliance reporting page in the resource manager. This report is a snapshot in time that compares the current state with the desired state.

It should be possible to:

- get a list of reports of a dryrun against the active desired state (all others should be ignored)
- request a new one
- fetch a pdf? https://react-pdf.org/components

**Comment by LauraStordeur** [comment]
Fetch a pdf, as in generate a pdf on the client/front-end or fetching it from our server? 

I skimmed through the documentation of the React PDF, and the generation seems to be on the client-side. Performance wise, I'm not yet convinced this is the best. Always was told that pdf generation shouldn't be done on the client. But then again, the users using the apps I worked on were not the same type of user. Client side generation can be heavy depending on the type of content you need to create. 

In me previous experiences, we always generated the pdfs on our servers, with our own templates. they used a python library to assemble the reusable components depending on the type of report they needed to generate.  Not saying this is a must, but maybe worth consideration if the idea is to have more than just one pdf report in the future. (Patternfly has the html version available of their components, so this is perfectly an option to create templates that have a design in line with the app) Not so sure we would be able to achieve the same with the React-pdf library.
