### ISSUE TITLE
Make resources requirements in resource details page clickable

### ISSUE THREAD

**Issue by sanderr** [inmanta/web-console#2563]
In a number of views we list the requires (both in the resource manager and the desired state). Each resource name should link to the corresponding details.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2563?planning-poker) with ZenHub @andraskvr @Stijnkool
