### ISSUE TITLE
Updating attributes of an instance with embedded entities doesn't work correctly

### ISSUE THREAD

**Issue by andraskvr** [inmanta/web-console#2607]
Updates on an instance of the following entity (with non-empty `disks` and `network-interfaces` properties) fail.
[https://app.zenhub.com/files/209321501/e1882b80-b626-441b-a508-8b5697949fa6/download](https://app.zenhub.com/files/209321501/e1882b80-b626-441b-a508-8b5697949fa6/download)
Changing for example the `description` sends a request with the payload:
`attributes: {description: "Server1", disks: [{}, {}], network_interfaces: [{}, {}, {}]}`
So an empty object for each `disk` and `network_interface`, that haven't even been changed.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2607?planning-poker) with ZenHub @andraskvr @Stijnkool
