### ISSUE TITLE
Refactor FilterPicker

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2611]
This component is always the same but we define it from scratch for every page.
We should be able to create a generic component for this that is then used in all pages.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2611?planning-poker) with ZenHub @andraskvr @Stijnkool

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2611?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
