### ISSUE TITLE
Injector should not reload on navigate

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2612]
Currently we use the location hook inside the Injector.
So on location change, all the classes get created again.
This has not really been an issue. But it came up when logging the jsonParserId.
That option is logged once in the constructor of the feature manager.
But on navigate, the feature manager is constructed again so it logs again.

The injector should not trigger again on location change.
Its dependencies should trigger again on location change.
If we just move the useLocation hook down to where it is used, it should be fixed.
But this might have some unforeseen effects that we need to check.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2612?planning-poker) with ZenHub @andraskvr @Stijnkool

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2612?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
