### ISSUE TITLE
Add support to view formatted traceback in resource log

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/web-console#2619]
The web-console shows the `kwargs`, part of the resource log entry as a dictionary. This way the traceback of a deployment failure becomes hard to read. This issue proposes to add support to view the traceback in a formatted way, i.e. with the interpretation of all special characters.

![traceback](https://user-images.githubusercontent.com/2684622/152151619-d8ad5157-e11d-4f2b-bc3a-626028e4c45b.png)

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2619?planning-poker) with ZenHub @andraskvr @Stijnkool
