### ISSUE TITLE
FileFetcher doesn't work correctly

### ISSUE THREAD

**Issue by andraskvr** [inmanta/web-console#2622]
The `FileFetcher` expects the response from the `/v1/file/<id>` endpoint to have the content in an envelope called `data`.
Since this is a v1 endpoint, the `data` envelope is not used, the access to the content should be just `response.content` instead of `response.data.content` in the `unpack` method:
 https://github.com/inmanta/web-console/blob/f64ad30fc9055d9b40d0cb653283213b1e7803ee/src/Data/API/FileFetcherImpl.ts#L44

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2622?planning-poker) with ZenHub @andraskvr @Stijnkool
