### ISSUE TITLE
Resource Id is not url encoded when querying facts

### ISSUE THREAD

**Issue by andraskvr** [inmanta/web-console#2623]
When querying the facts of a resource, the resource id should be url encoded, otherwise it might not be parsed correctly, for example: 
`std::File[example.inmanta.com,path=/tmp/yum.repos.d/epel.repo]`
Note that it's enough if this happens when firing the backend requests, on the UI we should still show the unencoded values.

We should also check if the resource id is encoded correctly for other queries

It would be  good to fix it for all parameters in the get call. All other encoding before should be removed so there is no double encoding.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2623?planning-poker) with ZenHub @andraskvr @Stijnkool
