### ISSUE TITLE
Configuration Tab should scroll horizontally

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2628]
![Screenshot 2022-02-02 at 16.39.17.png](https://images.zenhubusercontent.com/5ff6d00bc83e866b30a3b040/921c233a-83e6-4e94-99e2-a308b4eabe8c)
When the screen is too small, the controls are not accessible at all.
A horizontal scroll should be added.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2628?planning-poker) with ZenHub @andraskvr @Stijnkool
