### ISSUE TITLE
Jest testing is slow

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2629]
Can we tweak jest settings to improve this?
Might be ts-jest related.
https://stackoverflow.com/questions/45087018/jest-simple-tests-are-slow
This is mainly a concern during development.
I have not looked into the speed of the tests on jenkins.

## Ideas
- tweak ts-jest settings
- coverage setting, is this used somewhere? Can it be disabled locally?
- tweak other settings?
- Should we look into test duration on jenkins?

Timebox to 2h

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2629?planning-poker) with ZenHub @andraskvr @Stijnkool

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2629?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
