### ISSUE TITLE
Allow the useUrlStateWithFilter hook to handle multiple keys of complex types

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2632]
Currently this hook only supports:
- 1 key of IntRange
- 1 key of DateRange
- 1 key of BooleanRange

We should change this to a config object where you can supply any amount of properties.

So instead of:
```
interface Keys {
  dateRangeKey?: string;
  intRangeKey?: string;
  booleanKey?: string;
}
```
We need:
```
type Keys = Record<string, "IntRange" | "DateRange" | "Boolean">;
```
And then we just need to check and handle all the keys in this object.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2632?planning-poker) with ZenHub @andraskvr @Stijnkool

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2632?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
