### ISSUE TITLE
Long desired state attribute name overlaps in Resource Details views

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2696]
![image.png](https://images.zenhubusercontent.com/5ff6d00bc83e866b30a3b040/62d49361-9e4f-42c8-ac86-86e9477c7b6a)![image (1).png](https://images.zenhubusercontent.com/5ff6d00bc83e866b30a3b040/dbadc0aa-0c78-40a6-a14a-ae07839e0a6a)

We should probably make the name wrap to the next line when it's really long.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2696?planning-poker) with ZenHub @andraskvr @Stijnkool @wouterdb
