### ISSUE TITLE
Add highlighting to the compile logs

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2775]
In the old dashboard compile logs are highlighted. This makes them a bit easier to read.

The goal of this ticket is to also add this to the web console.

Unless there are complications this should also go into ISO4

Formatting per field:

Command: shell/bash/console
Err stream and output stream: as logs or python

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2775?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
