### ISSUE TITLE
Render json strings in the service instance attributes

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2801]
Because of limitations in the API we store JSON in some attributes. These are shown as strings, however this is not very readable for users.

The goal of this ticket is to render a value as json when it is valid json. Do a stringify

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2801?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
