### ISSUE TITLE
Improve timepicker

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2802]
The validation of the timepicker when typing acts really strange.

1. Fix the time validation
2. Fix the alignment on error
3. Date picker year is not visible
4. Support both slashes and dashes

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2802?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
