### ISSUE TITLE
Fix date formatting inconsistencies

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2805]
There are dates in many places in the web-console. However, there does not seem to be a common formatting. 

The goal of this ticket is to find all instances and clean them up. The recommended format is: YYYY/MM/DD HH:ii:ss 

Milliseconds are rarely useful to show

- In the new facts the correct date is used.
- In the compile report this is shown: ![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/1aa372a6-2790-43d5-a89e-0855f46a37f1)
- On the service instance details a long format is used.
- In the service instance history, on the tab of a version the date is not formatted at all
- ...

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2805?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
