### ISSUE TITLE
Home loading view is broken

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#2843]
For some reason this is broken again.
The loading state needs to be on a white background.
I am not sure what changed.

![Screenshot 2022-02-24 at 11.39.39.png](https://images.zenhubusercontent.com/5ff6d00bc83e866b30a3b040/f5e3f61b-ad47-43f7-9a3d-e25fe9435da3)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2843?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
