### ISSUE TITLE
Improve resource facts tab

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2860]
There are a number of issues with the provided table.

1. The data is not formatted (same issue as the other table?!?)

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/e85b0292-5140-4507-ae57-8ff19b4250de)

2. Most space should be reserved for the value. The name is often not that long. The data (when formatted) has a fixed length.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2860?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
