### ISSUE TITLE
Show service identity on the edit page

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2864]
cfr #2862

This page already fetches the service instance. So the description does not need to fetch it again.

## Todo
- [x] Add custom description component without data fetch

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2864?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
