### ISSUE TITLE
Cancel on edit clears the tab state in service inventory

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2866]
When you click the cancel button (maybe also confirm) it will also reset the open tabs. This means you need to search for the row you had open.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2866?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
