### ISSUE TITLE
Service history page should mention the identity or uuid

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2867]
cfr #2862

## Todo
- [x] Use custom ServiceInstanceDescription component with data fetching

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2867?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
