### ISSUE TITLE
Improve service instance history view.

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2868]
The service instance history page should be optimized. 

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/096b648e-586a-4c13-bd2f-1d60b3597d61)

1. Rename the timestamp field to something meaningful. For example: Created
2. Use our "default" absolute timestamp
3. Remove the details tab because it now longer has any additional value.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2868?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
