### ISSUE TITLE
Only show the resource id str (not version str) in the resources tab

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2870]
In the resources tab of the service inventory the full resource version id is shown. This should become only the resource id.

The name of the column should also just be "Resource" and not "Resource id"

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2870?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
