### ISSUE TITLE
Fix alignment on the tabs in the service inventory

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2872]
![Inmanta Web Console (1).gif](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/79f9b808-2bb6-4464-9ac8-81935fa1cd05)

The attributes table is header is aligned entirely different than the others tabs.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2872?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool

**Comment by Stijnkool** [comment]
Was resolved by other tickets.
https://github.com/inmanta/web-console/issues/2871
