### ISSUE TITLE
Disable the config tab when there are no settings to show

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2873]
The config tab should be disabled when there are not settings to show on the configuration tab of the service instance

This is a property of the service catalog entry

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2873?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
