### ISSUE TITLE
The jump to list in compare always shows disabled scrollbars

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2874]
![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/4b248f7f-25b4-4826-83d8-c27773ff4a6f)

I doubt if the horizontal is actually needed. The headers of the diff fields have the same font size so it the select box would not fit on the page, they will not either.

This is on chrome

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2874?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
