### ISSUE TITLE
Use primary toggle on desired state page for Recompile

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2876]
Currently there is no visual difference between a filter selection box and the recompile action. It should become a button with a dropdown. This is also the primary action, so it should be marked as such.

See this link for the patternfly component:
https://www.patternfly.org/v4/components/dropdown/#primary-toggle

The button should also be placed after the compare component.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2876?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
