### ISSUE TITLE
Use the same fontsize for Compare version widget

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2877]
The compare version widget uses a smaller font size than all other components in the toolbar. (14 vs 16px)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2877?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
