### ISSUE TITLE
Improve the dependencies column in the resources view

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2878]
1. The column should be named Dependencies
2. The toggle mark should be before the number

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/cf3fe5f4-97ff-4806-afe9-50c7d8685766)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2878?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
