### ISSUE TITLE
Improve actions on resources table

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2879]
The resource table has a button at the end of the row which does not in line with the patternfly design guidelines.

The goal of this ticket is to:

1. Remove the action header from the column
2. Replace the button with an action link
3. Use an action "Show details" instead of "Details"

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/cca5931b-9dbb-49e9-9854-310a3944d722)

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/d5941a5a-d9e8-41a7-9674-28e3f925e32a)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2879?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
