### ISSUE TITLE
Fix strange loading during paging on the resource page

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2881]
The resources table loads very strange when doing paging. Cfr discussions of a few weeks ago when talking about the performance.

![Inmanta Web Console (3).gif](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/e8992130-a817-429f-8565-2fe6b490f514)

Only the table should reload. The progress bar and the paging components should stay visible, like the filter.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2881?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
