### ISSUE TITLE
Make compile report table consistent

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2993]
The compile report table is not consistent with other views.

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/1a509075-7196-4482-8206-917e56207f00)

~~1. The column that contains the spinner when a compile is in progress seems to have a dynamic width. This creates a large white space~~
2. The actions column show not have a header
3. Use an action link with "Show details"
4. Align the actions to the end of the table

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2993?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
