### ISSUE TITLE
Compile report page should refresh the table after pressing recompile

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2994]
When you click recompile a new compile is added to the queue. Depending on the refresh interval it can take some time for it to show.

It would be better to reload the table after the recompile call returned.

![Inmanta Web Console (4).gif](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/2a46e061-b200-4f02-910b-863d92178f3e)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2994?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
