### ISSUE TITLE
Add a status field to the compile report table

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2996]
The compile report table now makes the status implicit by using colored rows. This is not consistent with other view and make the filter not clear.

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/70ddab76-c88d-4666-a370-8649e9f68fdf)

The goal of the ticket is to:

- Split out the Finished status (no longer a finished state) in to Success and Failed in status and remove the result
- Use one filter box that translates this to the correct api filters
- Add a field that shows the status of the report (In Progress, Success, Failed and Queued)
- Use labels for the status (green, red and blue for in progress and white/grey for queued)
- Show the waiting indicator next to the In Progress status
- Remove the first column

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2996?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
