### ISSUE TITLE
Improve agent table consistency

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2998]
![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/821b34d4-3ffb-4a6a-abff-e8710420b712)

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/c260c208-d03a-40f4-9962-f309615b9916)

1. Remove actions header
2. Align actions + kebab to the right of the table
3. Use links for the processes instead of buttons
3. Rename the unpause header to "On resume"
4. The size of the columns is strange (see screenshot 2). Non of the items in the first column (even if you scroll down) fill the first columns. But still the Unpause header is ellipsed.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2998?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
