### ISSUE TITLE
Make logs view consistent

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#3002]
![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/ff6fefe3-379c-482c-81de-f0a3bd0f4f35)

- The options header should be removed
- The kebab menu should move to the right
- Make the column a fixed size

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/3002?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
