### ISSUE TITLE
Agent process page is missing the name of the process

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#3006]
The name of the process should be mentioned on the process page. This can be part of the title.

For example: Agent process mgmt.ii.inmanta.com

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/449c2a0f-52bc-4c24-8bf8-8f271504d963)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/3006?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
