### ISSUE TITLE
Decode file content when showing its value

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#3008]
The content of a file is returned base 64 encoded. The resource desired state (resource manager and orchestration engine) do not decode this.

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/c86fcdf1-7c1d-4b1b-b230-2b79b498acfa)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/3008?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
