### ISSUE TITLE
Make resource table in desired state in line with other actions

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#3009]
![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/eab2567f-aa31-4352-82e8-83fd703b0050)

- The actions header should go
- The button should become a link with "Show details"

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/3009?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
