### ISSUE TITLE
Order of stages in compile report sometimes reverse

### ISSUE THREAD

**Issue by wouterdb** [inmanta/web-console#3082]
Sometime, during a compile, the order of the stages in the compile report view reverses order.

The goal of this ticket is:
- Figure out if the data is sorted in the backend
- Fix in backend or in web-console depending on where the problem lies.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/3082?planning-poker) with ZenHub @andraskvr @Stijnkool
