### ISSUE TITLE
Lsm dictionary fields with a default value don't render correctly.

### ISSUE THREAD

**Issue by wouterdb** [inmanta/web-console#3087]
![image](https://user-images.githubusercontent.com/1788254/157891570-d8dc7ccf-2350-45c1-9038-fef11405751c.png)

```
    dict influxdb_tags = {}
```

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/3087?planning-poker) with ZenHub @andraskvr @Stijnkool
