### ISSUE TITLE
Within a new environment, the recompile button is disabled while the server_compile setting shows enabled

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#3188]
### Problem
Within a new environment, the recompile button is disabled while the server_compile setting shows enabled.

### API
A new environment does not have the `server_compile` setting set.
The backend response does not return this property and is therefor undefined.

### web-console
On the configuration tab of the settings page, the server_compile setting is shown as enabled.
This is the default value. The default value is used for undefined settings.

The web-console never uses any of the settings. These settings have no effect on the web-console.
It is just data shown to the user.
Except for the `server_compile` property. It is used to disable the Recompile button.

### Fix
Does the frontend need to use the default value for any settings it uses that are undefined?
Or does the backend need to return default values?

**Comment by Stijnkool** [comment]
@bartv
Does the frontend need to use the default value for any settings it uses that are undefined?
Or does the backend need to return default values?

**Comment by bartv** [comment]
This should be implemented in the webconsole
