### ISSUE TITLE
Tracback in logs is rendered in normal fonts

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#3241]
![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/fc5a65a0-ab7f-4f79-a122-30a2da06dcc5)

All attributes should be monospaced, multiline strings should use syntax highlighter.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/3241?planning-poker) with ZenHub @andraskvr @FloLey
