### ISSUE TITLE
Long json string attributes are rendered incorrectly in the inventory view

### ISSUE THREAD

**Issue by andraskvr** [inmanta/web-console#3319]
There are 2 separate issues with json strings (strings that contain a json):

1. If multiple attribute sets have values for such an attribute, the cells are not truncated (but they should be).

2. In case the popover is shown, but the string doesn't fit on the screen when formatted, it's not possible to either scroll to the bottom of the popover, nor to go to the top where the clipboard copy button should be visible (but isn't). 
A quick fix for this would be a scrollbar, or we can also figure out some other way to show these attributes.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/3319?planning-poker) with ZenHub @andraskvr @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
