### ISSUE TITLE
Browser crashes when url keeps growing

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#3869]
When you open and close instance in the service inventory the url grows longer and longer. This crashes the browser at some point. This was already fixed for resource logs in #2680

https://code.inmanta.com/solutions/bics/bics_ce/-/issues/135

**Comment by LauraStordeur** [comment]
The link in the description to the bics issue is returning 404, but, I had a look at the fix that was done before. 

I'm not that well versed in everything that concerns parsing, so I might be wrong too. But, currently there is a limit set to 200 for the array being passed to the parser to transform it into an object. 
The package used for the parsing is this one: https://www.npmjs.com/package/qs

If I understand the documentation well; for example: 
`http://example.com?fruits=Banana&fruits=Apple`

would become the following object : 
`{ fruits: [ 'Banana', 'Apples' ] }`

The limit that was set in the previous fix would mean that the parsing would break when hitting over 200 fruits (arguments/queries)

There usually is a reason why a limit is imposed, it prevents extreme long queries that might overload the system. So I'm wondering what limit we can actually set that would satisfy all needs, and still prevent DOS.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/3869?planning-poker) with Zenhub @LauraStordeur @matborowczyk
