### ISSUE TITLE
Show notification when a newer version of the web-console is available

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/web-console#3879]
When the Inmanta server is upgraded to a new version that contains a newer version of the web-console, the user must do a force reload of the application in the browser to actually use that new version. This issue should make sure that the user gets notified when he/she is using an old version of the web-console while a new version is available on the server.

The status page already contains the commit hash, it could be used to detect a different available version as well:

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/0c199c3a-156d-4d51-8070-08fe609897df)

**Comment by LauraStordeur** [comment]
Notification, as in a toast/popup, or a banner that remains visible?

**Comment by LauraStordeur** [comment]
Okay! An orange one I assume?

**Comment by bartv** [comment]
The orange seems to be pretty in your face. I like the design in this screenshot:

![image](https://user-images.githubusercontent.com/10819/188887023-71b43280-7d8e-4618-8a2f-ec1c1c0be98d.png)

Any reason why you would use orange?

**Comment by LauraStordeur** [comment]
Orange is typically used for more or less important warnings. If the fact that the user is using an older version is problematic, from a UI-UX point of view, orange is the right choice. If the update of the version is not critical/that important, blue would do as it is then more an information than a warning.

**Comment by bartv** [comment]
lets do orange then

**Comment by LauraStordeur** [comment]
Okay, if it still feels too strong for the eye, we can still change the color later. That's a minor adjustment to do.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/3879?planning-poker) with Zenhub @LauraStordeur @matborowczyk

**Comment by LauraStordeur** [comment]
Status update : 
- currently the commitHash is being stored in the application when it is deployed. It is a configuration in webpack. 
- The problem is that it is a saved image, and hasn't any awareness of what's happening further in the repo. 

- Ideally, we would need an api-call to retrieve this information to be able to know if the app is outdated.  
Question : How do we proceed when this kind of situation occurs? @bartv
