### ISSUE TITLE
Delete env does not redirect

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#3924]
When an environment is delete, it does not redirect to the overview. Resulting in an exception and blank page.

- The app should not crash on wrong env!
- After delete it should redirect

I was only able to do this once. I cannot reproduce it again. The goal of this ticket is to look critically at the existing code to see if there are any conditions that could make it go wrong and then fix it.

It looks like it is related to the refresh running in the background.

The following recording show the flow:

![Inmanta Web Console (4).gif](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/792c96eb-c00a-404b-82cd-5cc6c5a80753)

**Comment by LauraStordeur** [comment]
Okay, so I've been testing around, I found out that the app has some difficulties when the network is kindof slow. I couldn't trigger a blank page, and the redirection seems to work in a lot of different cases. The errors are thrown in the console when the connection is not fast enough. These are the errors I'm managing to trigger. 
I have no idea yet what the scope of such issue could be in the current codebase. Do I make a separate ticket for this? 

![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/b8468c17-70d9-402a-9692-0a13b927beb)

**Comment by LauraStordeur** [comment]
![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/1124ffc0-12ee-4c25-820a-7a13103db660)

Managed to trigger a blank page, steps executed: Slow Throttle set on slow 3G, create new environment, edit name, put back normal connection, delete env => blank page.
