### ISSUE TITLE
Add compile in progress indication

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#3950]
When you are on the compile reports page and a compilation is in progress you see a spinner on that page. 

![Inmanta Web Console (8).gif](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/f36e3372-c993-45f1-9ea4-10eb757b5bef)

It would be useful to also show some indicator in the menu next to compile reports. Because now there are many actions in the background that depend on this and now it often looks like nothing is going on.

The old frontend did not suffer that hard from it because the main views always had the compiling button visible.

There are multiple options for this:

- Add a spinner. This is very visible which is both positive and negative because it also can become very annoying.
- Show a mark (like a bue dot)
- ...

**Comment by LauraStordeur** [comment]
A spinner? Or rather a tag? Or a progress bar, also possible depending if there is a indication on the progress of the compilation. 
Is something similar already used somewhere? 
Also where? :D

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/3950?planning-poker) with Zenhub @LauraStordeur @matborowczyk

**Comment by matborowczyk** [comment]
There is no efficient way to implement it, we can think about changing endpoint to serve data via websocket, but that also adds some work on backend and we would have to investigate if our current queryManager would handle that kind of endpoint out of the box

**Comment by bartv** [comment]
We already have quite some regularly polled endpoints. In the old frontend we used this API for that: https://docs.inmanta.com/community/latest/reference/openapi.html#tag/core.compiler/operation/is_compiling

**Comment by matborowczyk** [comment]
But that will still be an HTTP request that should be sent every 5 seconds, or so, practically as long as app is opened, do we want that?

**Comment by bartv** [comment]
We are already doing this for multiple endpoints. If this at some point becomes an issue, we will handle it then.

**Comment by LauraStordeur** [comment]
Since it's only for the active environment, I suppose it should be fine @matborowczyk 
The endpoint Bart mentions is a cheap one to do and will return you a boolean.

**Comment by matborowczyk** [comment]
Okay, wanted to double check. thank you!
