### ISSUE TITLE
KeyCloakInstance deprecated

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4002]
The used Class can be replaced with Keycloak.

In some places the constructor needs to be updated. 

![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/a2d04c37-cd33-428b-84cc-f0239a4c821e)
![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/bedab6cc-02ff-43ab-ba89-4afaf7a37e2d)

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4002?planning-poker) with Zenhub @LauraStordeur @matborowczyk
