### ISSUE TITLE
Autocomplete Accessibility behavior on Create Environment

### ISSUE THREAD

**Issue by LukasStordeur** [inmanta/web-console#4039]
The first Autocomplete element on the page is behaving oddly. Both with keyboard navigation as with the mouse. Quite annoying... Tabbing out of it sometimes put an old value not even in the list, and clicking outside when removing the value doesn't always clear the field. 

![autocomplete-weird-behavior.gif](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/330edba2-853a-4d50-bf4f-12d8db24c26c)

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4039?planning-poker) with Zenhub @LauraStordeur @matborowczyk

**Comment by LukasStordeur** [comment]
Mostly resolved in PF5 upgrade, also, this is a design choice of the library we are using
