### ISSUE TITLE
Issue with switches for demo

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4064]
URL HOST: http://192.168.2.16:8888/
(need to be proxied with LCP instead of your docker container) 

http://192.168.2.16:8888/console/lsm/catalog?env=919f42ca-22c2-4791-9965-2b8927e93550&state.Catalog.expansion[0]=cbci&state.Catalog.tab-cbci=config

Issue occurs when trying to change one of the config switches in the service catalog. 
The url is constructed with an error (two slashes instead of argument)

![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/813e06ba-c3ba-49e3-b791-fc72396a466c)

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4064?planning-poker) with Zenhub @LauraStordeur @matborowczyk
