### ISSUE TITLE
Service filtering when clicking on service relation doesn't work 

### ISSUE THREAD

**Issue by edvgui** [inmanta/web-console#4099]
If I click on the relation to the `back_bone` service in the attributes of the mobile core service here:
![image](https://user-images.githubusercontent.com/20844316/192285564-1f84a955-00dd-4796-bd76-7dbebe819341.png)

I end up here, with no `back_bone` being displayed: (The filter seems correct, but I would expect the service being filtered to be shown)
![image](https://user-images.githubusercontent.com/20844316/192285743-1263201d-1e96-4fd5-bfcf-77afab1586bc.png)

https://user-images.githubusercontent.com/20844316/192288756-8f02a21c-1f97-4ce9-8391-0f6cd5d98917.mp4

Web console commit hash: `edd03185e0ba74af29f03b80050702b17e5e3d9d`  
Service orchestrator version: `    5.2.1.dev20220926031235`

[db_dump.zip](https://github.com/inmanta/web-console/files/9646441/db_dump.zip)
> This db dump contains credentials to access the 5g lab (if you are in our internal network), you can mess up with it as much as you like, as long as @bartv is not doing a demo at the same time as you.  (If you leave the environment stopped this is fine)

**Comment by bartv** [comment]
The reason this does not work is that the value of the label "id" depends on whether there is a service identity or not. In case of the 5g demo an attribute is used as the identity in the first column.

If the attribute has a value instead of a UUID, then that value should be set in the filter and not the uuid.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4099?planning-poker) with Zenhub @LauraStordeur @matborowczyk
