### ISSUE TITLE
Display values in the app could be user friendlier

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4114]
In a lot of places, the snake-cased value is being displayed as a label. Where possible it would be nice to either get a title value that we can display to the user, or use a snake-case to capitalized casing transformer where the values are not dynamicly set. 

![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/dcb2952d-09ea-40c8-a833-ac1c9ff5f2de)
![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/2980212c-efbd-4a5e-b5f3-1265cb4b2ffe)

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4114?planning-poker) with Zenhub @LauraStordeur @matborowczyk
