### ISSUE TITLE
User feedback on edit config Environment

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4117]
At the moment there is no user feedback to inform the user the changes has been saved correctly. 
It would be a nice thing to have a snackbar/toast to inform of the success/failure of the action. 

![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/296ed935-773e-4280-8657-01f5ae9233af)

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4117?planning-poker) with Zenhub @LauraStordeur @matborowczyk
