### ISSUE TITLE
Green check on Compile Report even when report failed

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4118]
Even if the compile failed, the last check will still be green. It should be red.

![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/67b5ea1c-6900-4767-9d0c-a661789613c3
)

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4118?planning-poker) with Zenhub @LauraStordeur @matborowczyk
