### ISSUE TITLE
Overlay Navigation should close when clicked outside container

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4119]
The navigation bar could be improved UX wise by allowing it to close when the user clicks anywhere in the interface except in the navigation. (Need to check on Patternfly how, this should be expected behavior for overlay nav-bars)
![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/5f378bf6-3f91-45dc-a173-5645ad90b22e
)

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4119?planning-poker) with Zenhub @LauraStordeur @matborowczyk
