### ISSUE TITLE
Environment Select shouldn't appear on newline if there is enough space

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4121]
The select component in the navigation bar shouldn't go onto a new line if there is more than enough space to display it besided the Inmanta Logo
![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/c1e5be23-825a-498b-8dc6-f539bef6f0f7)

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4121?planning-poker) with Zenhub @LauraStordeur @matborowczyk
