### ISSUE TITLE
Table collapsibles behavior improvement

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4122]
Collapsible rows should be alligned throughout the app. Atm there are multiple implementations. Open for suggestions.

![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/56e11594-4656-4361-a461-a1c416d0f38f
)

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4122?planning-poker) with Zenhub @LauraStordeur @matborowczyk
