### ISSUE TITLE
Align capitalization "Show Detail"

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4123]
![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/d869af1c-a366-4e41-8d10-e7e025ab900b)

Should be Title cased.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4123?planning-poker) with Zenhub @LauraStordeur @matborowczyk
