### ISSUE TITLE
Inform user when he leaves unsaved form

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4125]
When you are filling a form it is currently possible to leave the form. The user should be informed that he is losing unsaved changes. This can be done by having a "isDirty" state in the form and showing an alert/modal that would prevent the user from leaving the page unknowingly.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4125?planning-poker) with Zenhub @LauraStordeur @matborowczyk
