### ISSUE TITLE
Improve repetitive section of forms with multi-select (or other suggestion)

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4126]
For better userexperience and developer experience aswell, it would be nicer to handle repetitive sections like these with something else than a expandable input/select field that is being repeated. We could use a multi-select for example.

![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/ce7e8ea3-aba5-4a73-a407-bb28f1ffe5d6)

**Comment by bartv** [comment]
At the moment this is specifically for relations to other service instances.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4126?planning-poker) with Zenhub @LauraStordeur @matborowczyk
