### ISSUE TITLE
When only one option available this one should be preselected

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4127]
For required values that are proposed in Select Components, it would be nicer to have the only available value preselected. This would avoid the user to have to click twice for something that he can't make a choice on. 

![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/8e9e8a4f-0002-4d7b-a82b-2f78086f5150)

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4127?planning-poker) with Zenhub @LauraStordeur @matborowczyk
