### ISSUE TITLE
Deployment progress bar not in sync with resources list

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/web-console#4138]
When a new service instance is created, the deployment progress bar shows the message `not resources available yet`. When resources become available, as can be seen from the resources tab, the deployment progress bar keeps showing the `no resources available yet` message instead of showing the actual progress.

[bug-deployment-progress-bar.webm](https://user-images.githubusercontent.com/2684622/193200760-f52a75fb-2a49-4869-8d82-4d16da5cc482.webm)

**Comment by bartv** [comment]
This is an issue in the backend not the frontend. See https://github.com/inmanta/inmanta-core/issues/4864
