### ISSUE TITLE
Make it more clear that multiple pages exist

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/web-console#4246]
When a table becomes too long, it is split into pages. I often find myself in the situation where I am looking for a resource and I cannot find it until I realize that the table got split into multiple pages and I am only seeing the first page. So it's not sufficiently clear for an end-user that more pages are available. I think this is caused by the fact that all paging buttons are at the right-top corner of the page. Most websites but these buttons at the bottom of the table. That way you automatically detect that there are more pages left when you reached the end of the table. I think we could improve the user experience by moving the paging buttons to the end of the table.

[Screencast from 10-21-2022 10:56:12 AM.webm](https://user-images.githubusercontent.com/2684622/197156546-cdbb9d6f-4742-4cd5-956b-11abc78270d1.webm)

Potential additional improvement: The top-right corner shows `1 - 20 of 35` to indicate that we are seeing the first 20 elements of 35 elements. In my opinion this expression is hard to read and it provides information almost no user is interested in. Most users just want to know on which page they are and they want the ability to increase/decrease the number of records on a single page. Wouldn't it be better to change this to `<page-nr>/<total-nr-of-pages>`

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4246?planning-poker) with Zenhub @LauraStordeur @matborowczyk

**Comment by LauraStordeur** [comment]
https://www.patternfly.org/v4/components/pagination/design-guidelines
