### ISSUE TITLE
e2e tests are made for specific environment

### ISSUE THREAD

**Issue by matborowczyk** [inmanta/web-console#4280]
Remove the old tests

**Comment by matborowczyk** [comment]
I discovered that e2e tests are specifically made for jenkins environment, so in case of breaking changes we firstly need to adjust them to work for local env, fix them, and convert to what is used in pipeline.

In addition I would like to point out that e2e covers only fraction of codebase

**Comment by bartv** [comment]
Port them to the real api using the local-setup

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4280?planning-poker) with Zenhub @LauraStordeur @matborowczyk

**Comment by matborowczyk** [comment]
Laura took care of it :)
