### ISSUE TITLE
Create Comments for commandManagers/QueryResolvers explaining use-case

### ISSUE THREAD

**Issue by matborowczyk** [inmanta/web-console#4292]

**Comment by matborowczyk** [comment]
At first glance implementation of backend communication is hard to read due to nested anonymous function, which sometimes doesn't give all information until seen in some component that use it which isn't optimal to work with them on daily basis, because that knowledge has high probability to vanish after some time. 
With Laura we came up with idea to make comment block to explain briefly or more thoroughly what is the flow of each commandManager and queryResolver, what are each parameters on each function(both initialisation, parameter callbacks and anonymous returned)

Both task about communication can be split into separate task for command Managers and QueryResolvers to sped up process

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4292?planning-poker) with Zenhub @LauraStordeur @matborowczyk
