### ISSUE TITLE
Double scrollbar falling off screen

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4294]
![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/7c689269-bd9d-4423-95a9-c8966a66d033)

When the content overflows, a second scrollbar pops up, and falls off screen. The overflow is badly handled, and should be improved.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4294?planning-poker) with Zenhub @LauraStordeur @matborowczyk

**Comment by LauraStordeur** [comment]
Did some checks, the issue comes up only when the update banner is being displayed. 

It's also an issue on the patternfly pages, the overflow is handled weirdly their too. The overflow is ending up in a double scrollbar. ![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/0d6a0107-ba59-47b5-8434-8b050ffae102)

I think resolving this edgecase would require a lot of overriding classes and tweaking the original layout. 

If it's okay, I'd like to close this issue for now, it can be reopened if anyone else reports this to be an issue. The content is still reachable, you just need to both containers down to reach the bottom of it all.
