### ISSUE TITLE
Extract hard-coded strings in Tests

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4296]
Most of the time values are being matched with hard-coded strings, while we have the `words` method where all printed values are being stored. It would make sense to use the `words` instead. It makes maintenance easier. When some texts in the UI change, like casings being aligned, we wouldn't have to hunt down all places where that string was hardcoded in tests.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4296?planning-poker) with Zenhub @LauraStordeur @matborowczyk
