### ISSUE TITLE
[E2E] Scenario 2.1 Service Catalog - basic-service

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4317]
# Scenario 2 : Service Catalog
Note: This scenario is assuming the usage of the lsm-module and requires the frontend-lsm-module repo to be pulled in with a script.

Before scenario make sure to execute the API call to clear the test-environment AND update call with the force flag set to true. 

### 2.1.1 Add Instance Cancel form
- Select the environment named 'test'
- Select Show Inventory on basic-service
- Expect no available instances in the table
- Click Add Instance
    *foreach field except last one*
    - fill in field
        **Valid configuration:**
            address_r1:		1.2.3.5/32	
            address_r2:		1.2.2.3/32	
            interface_r1_name:		eth0	
            interface_r2_name:		interface-vlan	
            ip_r1:		1.2.3.4	
            ip_r2:		1.2.2.1	
            service_id:		0001	
            should_fail:		false	
            vlan_id_r1:		1	
            vlan_id_r2:		0
- Click on Cancel  
- Expect alert if already implemented
- Expect to be redirected to Service Inventory
- Go back to home

### 2.1.2 Add Instance Submit form
- Select the environment named 'test'
- Select Show Inventory on basic-service
- Expect no available instances in the table
- Click Add Instance
    *foreach field except last one*
    - fill in field
- Click on Submit
- Expect to be redirected to Service Inventory
- Expect new instance to be visible in table
- Expect only Active Attribute icon to be dark
- Open element in table
- Click on attribute tab
- Expect it to match values entered at instance creation
- Click on Resource tab
- Expect 1 item in resource table
- Go back to home

### 2.1.3 Edit previously created instance
- Select the environment named 'test'
- Expect basic-service to have a badge
- Select Show Inventory on basic-service
- Expect 1 item to be still in table
- Click open element
- Expect to be on the status tab
- Click on edit
**Test invalid input**
- Remove the first value
- Submit form
- Expect Danger alert:Editing instance failed
- Edit first field value to 1.2.3.8
- Expect to be redirected to Service Invetory
- Expect Candidate Attributes icon to be dark
- Click open element
- Click on Attributes tab
- Expect Column Candidate, and Active to have values
- Expect changed field to have a different Candidate than Active value.
- Go to Status tab
- Expect create date to be different than update date
- Go back to home

### 2.1.3 Delete previously created instance
- Select the environment named 'test'
- Expect basic-service to have a badge
- Select Show Inventory on basic-service
- Expect 1 item to be still in table
- Click open element
- click on delete instance
- Expect modal
- Click on cancel
- Expect nothing changed in table 
- click on delete instance
- Confirm
- Expect table to be empty. (this takes a moment to be processed, might need a sleep timer on it.)
- click on breadcrumb Service Catalog option
- Expect basic-service to have no badge anymore
- Go back to home

**Comment by bartv** [comment]
A more stable alternative to a sleep timer is polling the UI or even polling the API until the value is gone (but then we still need to wait until the datastore refreshes)

**Comment by LauraStordeur** [comment]
Yes, I'll check what the best practices are concerning asyncs/awaits in cypress, and update the ticket
