### ISSUE TITLE
[UI/UX] Badge making rows in Service catalog irregular

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4322]
# Issue
At the moment the rows can have irregular heights depending on having instances or not. 

![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/a23006d1-59d4-40ec-9838-fef6bc9458a8)

# Proposed solution
Align the badges After the name of the service. In case of small screens, allow wrap to display the badges under the name.

![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/045277a4-0d96-436c-9553-e026a0c4530f)

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4322?planning-poker) with Zenhub @LauraStordeur @matborowczyk
