### ISSUE TITLE
[UX] Delete Service is not redirecting to catalog after deletion

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4326]
# Issue
When you go to the Service Details page, and you delete a Service, you are not being redirected to the Service Catalog. Instead you get an error in your page with the suggestion to retry. Which serves no purpose since the service doesn't exist anymore.

![delete-service-issue.gif](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/e9deb6c3-ea81-4d43-bd55-2bbb08d63aa6)

# Solution
Remove the button in this view and move it as an action into the kebab menu on the catalog page.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4326?planning-poker) with Zenhub @LauraStordeur @matborowczyk
