### ISSUE TITLE
[BUG] Filter by status dropdown crawling under Diff in Compare/Compliance check page

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4338]
# Issue
When clicking on the Filter by status dropdown, it will be displayed under the diff module header which allows you to jump to different sections. 

The same happens with the dropdown displaying the dates of the dry-runs on the Compliance page

![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/f2f39ff7-8d86-4a7d-8124-436a440aaef7)
![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/fb410664-fba5-4e66-9650-5433c87b3780)
![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/58cff837-0843-4201-ac28-c0ad23335fbc)

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4338?planning-poker) with Zenhub @LauraStordeur @matborowczyk
