### ISSUE TITLE
[DASHBOARD] 1.2 Adjust the routing and have the Dashboard in the navigation bar.

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4526]
Adjust navigation for :
- The click behavior on the Inmanta logo to redirect to the new page if an Environment is selected.
- Modify the route for the overview page to be "/console/overview" instead of "/console"

- Add the section in the navigation bar
- The Dashboard should be locked when no environment is selected.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/44098050/211324240-6e0737fb-9794-4077-a3ba-210e28594a88.png">

**Comment by matborowczyk** [comment]
done in #4533
