### ISSUE TITLE
Improve UX regarding the On Resume feature on the agents page

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/web-console#4555]
When an environment is halted, the agents page shows the `On resume` column. I see two issues here:

* I guess the toggle switches belong to the `On resume` column? But the switches are not correctly aligned with with respect to the column header.
* Next to that, it's not very clear from the title what the switch does. I had to hover the switch to know how it works. Wouldn't it be better to rename the column name to `unpause on resume`?

![Screenshot from 2023-01-19 08-49-26](https://user-images.githubusercontent.com/2684622/213385649-e07d93d7-07c1-49fe-b43d-a96dc0400124.png)

**Comment by bartv** [comment]
https://drive.google.com/file/d/1nNACB1f6k8iMhyvMNs74zeHWvAco-iFo/view
