### ISSUE TITLE
Tooltip flickering

### ISSUE THREAD

**Issue by Hugo-Inmanta** [inmanta/web-console#4612]
The tooltips for halted and resume buttons in the sidebar sometimes flicker when hovering over the button.

This was tested on iso6-next and iso5-next on firefox.

Steps to reproduce:

- Hover over the Stop (or Resume) button of the sidebar
- The tooltip sometimes briefly appears on top of the button and then snaps to the right of it

**Comment by bartv** [comment]
@Hugo-Inmanta can you add a recording of this?

**Comment by Hugo-Inmanta** [comment]
[Screencast from 09-02-2023 11:17:21.webm](https://user-images.githubusercontent.com/98876549/217784669-6c0ee0ac-e02c-400a-b092-447c3d0ec822.webm)
