### ISSUE TITLE
Axis of metrics graphs don't scale correctly

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/web-console#4626]
I observed the issue where the tooltip of the graph indicates that the value is 1, while the y-axis of the graph only goes up somewhere slightly above 0.5 (See image)

![axis_scaling](https://user-images.githubusercontent.com/2684622/218068238-a2539aea-71b6-4cb0-b563-ec4250afb6a9.png)

**Comment by matborowczyk** [comment]
@arnaudsjs Is there a chance to get json from that metrics? I couldn't reproduce issue with mocked data, I suspect that there was some rounding issue which wasn't sent to maxValue, but I'm not sure
