### ISSUE TITLE
Data shown in graph out of sync with tooltip

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/web-console#4627]
I observed the issue where the tooltip indicates the value is 1, but the line of the graph goes above 1 (See nolabel graph in image).

![graph_mismatches_tooltip](https://user-images.githubusercontent.com/2684622/218069048-5f993987-0153-4295-8bca-d189251f325b.png)

**Comment by bartv** [comment]
Try to snap to the values so that the tooltip does not show on lines between values.
