### ISSUE TITLE
User Management Implementation

### ISSUE THREAD

**Issue by LukasStordeur** [inmanta/web-console#4738]
![Image](https://user-images.githubusercontent.com/44098050/227968286-0d69e820-9c29-4269-882a-e83875af1048.png)

**Comment by LauraStordeur** [comment]
- There is no pagination on the endpoint, the FE has to handle it. 
- If the logged in user gets a 403, this means the user doesn't have the access to edit/view the User Management page. An error page can be shown for now until we have proper role assignment. 
- Edit / Create triggers a modal with the needed input fields. 
- Delete triggers a confirmation modal for the actions.
