### ISSUE TITLE
Different font sizes service details attributes vs callbacks/lifecycle

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#4752]
Two tabs in the service details have different font sizes (14 vs 16px)

https://user-images.githubusercontent.com/10819/228858404-5bc1434b-c4ce-479b-ad36-6f80cdc7e2cd.webm

**Comment by matborowczyk** [comment]
All of the Tabs have same font sizes (16px)

https://user-images.githubusercontent.com/113331659/235871307-3caa3de8-6395-47db-be01-f8a1dfc9d6eb.mov
