### ISSUE TITLE
Create a read-only canvas with a single instance

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#4754]
The goal of this ticket is to create a canvas with a single block that shows the name and the attributes. This feature should be behind a feature flag in config.js

If the flag is not present in config.js it should be interpreted as false

**Comment by LauraStordeur** [comment]
https://www.figma.com/file/RFtD78ZxDx2N28fV2XVnR8/Inmanta-Designs?node-id=15%3A145&t=qycuqCSFm7rbTF6h-1
You can find all the designs in Figma here if needed
