### ISSUE TITLE
resources page: restrict progress bar to filtered resources

### ISSUE THREAD

**Issue by sanderr** [inmanta/web-console#4783]
Currently the progress bar on the resources page is always for all resources rather than only the ones matching the filter. I think it would be more intuitive to only show the matching ones. The screenshot below shows that the filter matches only 45 resources but the bar shows a lot more.
![screenshot_2023-04-12-104653](https://user-images.githubusercontent.com/7672159/231404502-7099df7d-3d82-415f-94c5-068f67a33ed6.png)

**Comment by LauraStordeur** [comment]
@bartv I remember some discussions about this specifically. I believe it was desired behavior to always have the full bar even though some filtering might be active. Was there still things that needed to be discussed or proposed ?

**Comment by bartv** [comment]
It was indeed by design. Of course we can decide to change this. So not sure what to do with it. 

Given the priorities this is either icebox or close.
