### ISSUE TITLE
Value select does not work anymore in instance forms

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#4790]
When a field is an enum we show a select with the options. In the latest release 6.2.0 this is broken. It shows it for a required field but the optional field at the bottom does not have it

![Image](https://user-images.githubusercontent.com/10819/231986305-fbc55cce-66e1-4ec6-a0e3-99b6d432adc4.png)

In a version from 20230303 you can see that it still worked:

![Image](https://user-images.githubusercontent.com/10819/231986418-153986e6-1842-4c89-affe-592547611f82.png)

**Comment by matborowczyk** [comment]
Service provided by Dariush doesn't contain this issue. Sander mentioned last week that pushed something related to it so it could be that issue was on the other side of the application and no longer exist. @bartv

**Comment by bartv** [comment]
I tried it on the latest dev build and still the same problem. You can find an instance here: http://192.168.2.58:8888/console/lsm/catalog?env=3152e18f-87e6-48d8-bd54-7d9fa409d847
