### ISSUE TITLE
Resource details button on diagnose window directs to wrong URL

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/web-console#4907]
The `resource details` button on the diagnose window redirects to a URL where the resource id is truncated after the comma. The result is a 404 error.

The URL endpoint has the signature: `/console/resources/<resource_id>`. In the example below the resource id is `std::Service[arnaud.inmanta.com,name=inmanta-server]`, but the URL only contains `std::Service[arnaud.inmanta.com`.

[Screencast from 2023-06-16 14-17-56.webm](https://github.com/inmanta/web-console/assets/2684622/dcc817c9-866c-4130-a21d-719eb181001b)

**Comment by LauraStordeur** [comment]
https://github.com/inmanta/inmanta-core/issues/6220
Blocked for the moment by this ticket.
