### ISSUE TITLE
Returning from resource details view resets page number

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/web-console#4976]
* A user navigates to the resources view and requests the details of a resource present on a page larger than 1
* When the user clicks the back arrow from the resource details view, it is routed back to the first page of the resources view and not to the page the user came from.

[Screencast from 2023-07-18 07-44-42.webm](https://github.com/inmanta/web-console/assets/2684622/5008ebc7-1682-4850-a1ce-7d31b29b57f2)

**Comment by matborowczyk** [comment]
@LukasStordeur my propositions for that improvement is to modify behaviour of the pagination and introduce extra dependency to query. But that comes with question, do we want to introduce that in every place that pagination is available or only to that specific page. 
The changes itself doesn't seem to be complicated but they are at the root of components that are reused across this kind of pages.

Solution proposed:
change functions that are responsible to navigate through subpages from updating whole link to pass only parameter responsible for previous/next subpage back to the dependency list and from there keep track of current page.

**Comment by matborowczyk** [comment]
@LukasStordeur
