### ISSUE TITLE
Field that shows the content of a file has white bar at the bottom

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/web-console#4977]
When a user requests the content of a file for a `std::File` resource, a white bar is shown at the bottom of the text field.

[Screencast from 2023-07-18 07-56-53.webm](https://github.com/inmanta/web-console/assets/2684622/a6e6724c-38a2-4b18-ba40-08464294b963)

**Comment by LauraStordeur** [comment]
Adjust min-height in `web-console\src\UI\Components\CodeHighlighter\index.tsx`

**Comment by LauraStordeur** [comment]
Resolved in when updating the scroll behavior in the CodeHighlighter
