### ISSUE TITLE
Ask JointJS about linking bug

### ISSUE THREAD

**Issue by matborowczyk** [inmanta/web-console#5011]

**Comment by matborowczyk** [comment]
There is a weird bug with connecting shapes visible in the video below. I found a way to resolve it, but I don't know the source of the issue(whether is something that I have missed, or something on their side)

1. first part shows the problem that's about that the dimensions of the shapes are off when trying to connect one to the other. It only happens to freshly added shapes, that weren't focuse by the user so far.
2. refresh of the app is caused by adding `element.getBBox();` to the function that handles highlighting the shapes, which is enough to resolve the problem, probably because canvas/graph sets information about dimensions and the position of the entities.

https://github.com/inmanta/web-console/assets/113331659/ce2c0492-68b2-42c2-9e72-d0627c020cfd

I want to ask about this in the first incoming batch of questions. I don't think that is necessary to rush with that one, as I don't have anything else for them and I don't want to spend our support budget on a single question.

**Comment by LukasStordeur** [comment]
@matborowczyk any news on this?

**Comment by matborowczyk** [comment]
posted ticket to JointJS team, and tagged you just in case. Depending on response from them I'll create appropriate task
