### ISSUE TITLE
Cannot add embedded entities in edit form

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#5205]
When trying to add embedded entities to a list it is not possible to fill in the fields if they are not marked rw+

The edit rules are applied even if they are a new item.

https://drive.google.com/file/d/1atPbOeLHgZLwXzVUijDQzHNZIqDHitoV/view

**Comment by matborowczyk** [comment]
Is it possible that this issue got resolved? Checked against current master `embedded-entity-service-extra` which has `rw+` list of embedded entities, which one of the attributes is `rw`, and it works like intended


https://github.com/inmanta/web-console/assets/113331659/c139f791-b711-4f5a-982a-78354481c98e

**Comment by matborowczyk** [comment]
@bartv

**Comment by LukasStordeur** [comment]
Resolved in 7.1
