### ISSUE TITLE
Composer - Disable Deploy button when no changes

### ISSUE THREAD

**Issue by LukasStordeur** [inmanta/web-console#5275]
When no changes have been made to the model, we should disable the button.

**Comment by matborowczyk** [comment]
Should we recognise  if instance will return to its original attributes? here it's probably easier to implement than in regular Instance Form - but I don't think it will be that easy if user deletes shape(embedded or not) in composer and then creates shapes with the same attributes.

**Comment by LukasStordeur** [comment]
I suppose the easiest path is to enable the button from the moment the user submits any type of form

**Comment by matborowczyk** [comment]
That's right, I did that, but then started thinking if we want go further with that, but we can go back after I'll do everything from current epic

**Comment by LukasStordeur** [comment]
Yeah, I suspect the behavior will change anyway when you start working on persisting the positioning for example.
