### ISSUE TITLE
BUG - Pagination state

### ISSUE THREAD

**Issue by LukasStordeur** [inmanta/web-console#5314]
When I go to some resource logs and page through a few times and hit refresh, the page crashes. 

https://github.com/inmanta/web-console/assets/44098050/3ee7c5ea-009d-4fbe-af51-93bac3264ba0

**Comment by matborowczyk** [comment]
This issue happens on the whole Resource Logs view when proxying mgmt to local instance, everything points towards issues with router. specifically to backend routing, as it seems like this given route isn't recognized so we get 404.

Weird thing is that only occurs for one vie, only when proxying. I'll ask on stand-up if someone from core is willing to check on their side what could be going on

**Comment by matborowczyk** [comment]
It was agreed that it has something to do with proxying itself, and I'm out of ideas how to further investigate it, so I'll close that one as It doesn't have influence both on local development when proxying docker version, nor on the production.
