### ISSUE TITLE
Filetring on Compliance page and Compare page issues

### ISSUE THREAD

**Issue by LukasStordeur** [inmanta/web-console#5439]
The pages freezes and DDOS the server. See [Slack thread](https://inmanta.slack.com/archives/C045Y42N49W/p1704959160522119) for a DBDump to reproduce issue.

**Comment by matborowczyk** [comment]
closed by #5395

**Comment by matborowczyk** [comment]
I would need some more information to reproduce an error, did it happen locally, how many resources were there? I just checked on mgmt and it works just fine

**Comment by LukasStordeur** [comment]
The dump file can be found here : [slack thread](https://inmanta.slack.com/archives/CKRF0C8R3/p1706541667181359?thread_ts=1706541624.937709&cid=CKRF0C8R3)

The dryrun was around 700 resources. Joao was the one to observe it, and his browser froze entirely while the dryrun was completing. 

**Important, do not launch the DB without halting it by adding the line in the sql file first** It will try to connect to the network otherwise.
