### ISSUE TITLE
[Composer] Only make Composer accessible from Root Instance

### ISSUE THREAD

**Issue by LukasStordeur** [inmanta/web-console#5471]
When you create multiple instances and dependencies, you get redirected to the Service Inventory, which could perfectly remain empty if the user didn't create an instance of that type. 

Maybe it would be nicer to either redirect to the OrdersPage or the Service Catalog.

**Comment by LukasStordeur** [comment]
won't do the redirect => limitation of the options in the dropdown would resolve the fact that the inventory is empty.

**Comment by matborowczyk** [comment]
If I'm correct we can't straightforwardly tell which entities should be shown in the dropdown, I mean we can iterate through all services and check if any of relations are related to the selected core service, but that feels sub-optimal.

**Comment by LukasStordeur** [comment]
I believe that's something that this is a combined effort with the BackEnd. We need an indication which Services are considered as a root, and then you should be able to go through the instance model to retrieve the possible relations/embedded attribute models.

**Comment by bartv** [comment]
I have updated the front-end-lsm-test-model to include two entities with a parent/child relation. The logic that needs to be applied is that:

- Only services for which the owner field is null can be opened/edited/created direct in the composer
- Services with owner not set to null, need to be opened in the composer of the owner (and recursively up)
- Each owner, also has a list of direct children.

It is still possible to link entities from one "tree". I think we need to clearly mark those entities on the canvas (and in this stage even make them read-only?)

This looks as follows in the test repo:

![Image](https://github.com/inmanta/web-console/assets/10819/b1ff45b9-2eca-452c-ba12-b61e2ed7b346)
