### ISSUE TITLE
[Composer] Toggle connection labels

### ISSUE THREAD

**Issue by LukasStordeur** [inmanta/web-console#5480]
https://github.com/inmanta/web-console/assets/44098050/e4bea232-08c4-4fe8-b84c-7099fa1d2ba5

At the moment the second button in the toolbar is not doing anything. It is supposed to toggle the labels on the connections.

**Comment by matborowczyk** [comment]
What's the meaning behind that labels?

**Comment by LukasStordeur** [comment]
It's the name of the connection. Depending on the relation it can be a from-to connection in one direction, or in two directions. Let's discuss this in the planning meeting

**Comment by LukasStordeur** [comment]
If it starts with an underscore, we can assume the label can be hidden

**Comment by matborowczyk** [comment]
I got blocked/stuck with that problem as I got issue with proper display, distances are relative so the labes at the ends can be overflown by shapes, my solution to that base on event which isn't fired, I wrote a ticket to the jointJS team with question
