### ISSUE TITLE
Support scrolling down through the JSON editor window

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/web-console#5830]
In order to click the confirm button on the JSON editor, you might have to scroll down. However, if you mouse is positioned over the editor's text field, it will try to scroll within the text field. The general convention is that the entire browser window will scroll down if you keep on scrolling down while having reached the button of the embedded text field. That currently doesn't work for our JSON editor, but I think it would improve the user-experience by a lot if we would.

**Comment by LukasStordeur** [comment]
This is fixed on ISO8, when adjusting the page heights and aligning them throughout the app, it allowed to have the editor full height, without having an unnecessary scrollbar. It's an accidental fix that came when working on the layout for the new Instance Details. 

The question is, do we need to make the effort to have this in ISO7 too?

**Comment by LukasStordeur** [comment]
will be foxed only in iso8
