### ISSUE TITLE
Expand all doesn't expand eveything

### ISSUE THREAD

**Issue by Hugo-Inmanta** [inmanta/web-console#5956]
attachment:
[expand_all_doesnt_expand_everything.webm](https://github.com/user-attachments/assets/1719c841-6f60-4407-8e80-26a23a378692)

context:
    opening an item in the service inventory
    
bug:

    click kebab menu -> click expand all
    
    expected behaviour: Expand everything
    actual behaviour:   Only expands common attributes(?)

**Comment by LukasStordeur** [comment]
Issue will be resolved with the Instance Details page being finished. The content of the collapsible rows in the service inventory will be removed.
