### ISSUE TITLE
Field name for inter service relations is not shown

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#5959]
When inter service relation are defined it will use as field name "An instance of <other type>"

The documentation it shows is the documentation of the type of the relation, not the documentation attached to the relation. (this is a bug in the backend).

Consider the following catalog:

```json
{
        "inter_service_relations": [
          {
            "name": "untagged_vlan",
            "description": "A vlan in the network that can be used as tagged or untagged vlan on interfaces. A vlan can also\n\nhave IPv4 and IPv6 prefixes.",
            "modifier": "rw+",
            "attribute_annotations": {},
            "lower_limit": 0,
            "upper_limit": 1,
            "entity_type": "Vlan"
          },
          {
            "name": "tagged_vlans",
            "description": "A vlan in the network that can be used as tagged or untagged vlan on interfaces. A vlan can also\n\nhave IPv4 and IPv6 prefixes.",
            "modifier": "rw+",
            "attribute_annotations": {},
            "lower_limit": 0,
            "upper_limit": null,
            "entity_type": "Vlan"
          }
        ]
}
```

It will be shown as:

![image](https://github.com/user-attachments/assets/9f0e970e-4083-4667-911b-61e2abc4a6c0)

The expectation is that it shows the name of the relation as defined int he catalog. In this case: untagged_vlans and tagged_vlans

**Comment by LukasStordeur** [comment]
Duplicate, resolved
