### ISSUE TITLE
Provide a easy way to determine the version or commit hash of the web-console

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#679]
This might be useful because a lot of different versions of the web-console are used.
Solutions:
 - Show version/commithash in comments in index.html
 - Log version to the browser console on script start

This hash could be show on the status page in #1723

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/679?planning-poker) with ZenHub @bartv @Stijnkool

**Comment by wouterdb** [comment]
This may help: https://jenkins.inmanta.com/env-vars.html/
